language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

cache:
  directories:
    - vendor

install:
  - composer install

script:
  - vendor/bin/phpcs -p --standard=PSR2 --colors src tests
  - vendor/bin/phpunit

addons:
  artifacts:
    paths:
      - tmp/coverage
    debug: true
